language: python

python:
  - "3.6"

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

before_install:
  - sudo apt-get update -q
  - sudo apt-get install pass gnupg

install:
  - poetry install -v

script:
  - poetry run pytest